package org.jk;
import junit.framework.TestCase;

public class CalculatorTest extends TestCase {

	public void test_type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertNotNull(Calculator.class);
	}

	public void test_instantiation() throws Exception {
		// TODO auto-generated by JUnit Helper.
		Calculator target = new Calculator();
		assertNotNull(target);
	}

	public void test_add_A$int$int() throws Exception {
		// TODO auto-generated by JUnit Helper.
		Calculator target = new Calculator();
		int a = 0;
		int b = 0;
		long actual = target.add(a, b);
		long expected = 0L;
		assertEquals(expected, actual);
	}

	public void test_multiply_A$int$int() throws Exception {
		// TODO auto-generated by JUnit Helper.
		Calculator target = new Calculator();
		int a = 0;
		int b = 0;
		long actual = target.multiply(a, b);
		long expected = 0L;
		assertEquals(expected, actual);
	}

}
